name: "SMA Swasta"
address: "Jln R.A Kartini, Malang, Indonesia"
phone: "+62 341 123456"
email: "info@smaswasta.sch.id"
description: "Place of Excellence in Education"
attributes:
- key: "Established Year"
  value: 1995
  type: number
- key: "Principal"
  value: "Dr. Jane Smith"
- key: "Motto"
  value: "Empowering Future Leaders"
- key: "Number of Students"
  value: 1200
  type: number
- key: "Number of Teachers"
  value: 75
  type: number
- key: "School Colors"
  type: array
  value: [ "Green", "White" ]
- key: "Mascot"
  value: "Hawk"
